### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by czjdr** [HuanLinOTO/gradio-scaner#1]
请问这个报错能解决吗？说是map无法定义还有其它问题

child process exited with code 0 and signal null 1/13
node:events:491
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read properties of undefined (reading 'map')
    at /root/cs/index.js:81:44
    at Parser.<anonymous> (/root/cs/node_modules/xml2js/lib/parser.js:308:18)
    at Parser.emit (node:events:513:28)
    at SAXParser.onclosetag (/root/cs/node_modules/xml2js/lib/parser.js:266:26)
    at emit (/root/cs/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/root/cs/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/root/cs/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/root/cs/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/root/cs/node_modules/xml2js/lib/parser.js:327:31)
    at Parser.parseString (/root/cs/node_modules/xml2js/lib/parser.js:5:59)
Emitted 'error' event on Parser instance at:
    at Parser.exports.Parser.Parser.parseString (/root/cs/node_modules/xml2js/lib/parser.js:331:16)
    at Parser.parseString (/root/cs/node_modules/xml2js/lib/parser.js:5:59)
    at /root/cs/index.js:75:20
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)

**Comment by HuanLinOTO** [comment]
项目已经不能用了
